---
version: 2.1

executors:
  build-executor:
    docker:
      - image: quay.io/labmonkeys/cimg-base:2023.12-22.04.b72

commands:
  make-image:
    description: "Build OCI image and publish from main branch"
    parameters:
      workdir:
        default: "~/project"
        type: string
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build OCI image and publish from main branch
          command: |
            cd << parameters.workdir >> && pwd
            if git show --name-only --format='' . | grep ""; then
              echo "Changes detected trigger build"
              if [[ "${CIRCLE_BRANCH}" == "main" ]]; then make publish BUILD_VERSION_SUFFIX=".b${CIRCLE_BUILD_NUM}"; else make oci; fi
            else
              echo "No changes in directory << parameters.workdir >> detected, skip build."
            fi

workflows:
  version: 2

  build:
    jobs:
      - openjdk-11-jdk:
          context: "Publishing"
      - openjdk-11-jre:
          context: "Publishing"
      - openjdk-17-jdk:
          context: "Publishing"
      - openjdk-17-jre:
          context: "Publishing"

jobs:
  openjdk-11-jdk:
    executor: build-executor
    steps:
      - make-image:
          workdir: "./openjdk-11-jdk"

  openjdk-11-jre:
    executor: build-executor
    steps:
      - make-image:
          workdir: "./openjdk-11-jre"

  openjdk-17-jdk:
    executor: build-executor
    steps:
      - make-image:
          workdir: "./openjdk-17-jdk"

  openjdk-17-jre:
    executor: build-executor
    steps:
      - make-image:
          workdir: "./openjdk-17-jre"

